#!/bin/bash
# Copyright (C) 2024 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is to simply copy the input jar to the output jar.
# The real tool is developed internal and is not published to AOSP yet.
# This script will be replaced when the internal tool is ready.

invalid_arg() {
    echo "ApiMapper: invalid args" 1>&2
    exit 1
}

(( $# >= 4 )) || invalid_arg
[[ "$1" == "--in-jar" ]] || invalid_arg
[[ "$3" == "--out-jar" ]] || invalid_arg

echo "ApiMapper: copy $2 to $4"

cp "$2" "$4"
