// Copyright (C) 2026 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

// Contents from a file containing a list of blocked symbols, generated by
// blocked_symbol_list_to_cpp.py.
struct FileContent {
    // The name of the symbol map file, from which the list of blocked symbols
    // was generated.
    // Example: "libandroid.map.txt"
    const char* symbol_file_name;
    // The content of the file, containing a newline-delimited list of blocked
    // symbols.
    const char* content;
};
