// Copyright (C) 2026 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include <jni.h>

#include <cstddef>

#include "FileContent.h"

// Generated by denylist_symbol_list_to_cpp.py. Terminated by a nullptr entry.
extern const FileContent kFileContents[];

extern "C" JNIEXPORT jobjectArray JNICALL
Java_android_nativeservice_test_NativeNdkAllowlistTest_getFileContents(JNIEnv* env,
                                                                       jclass /* clazz */) {
    size_t count = 0;
    while (kFileContents[count].symbol_file_name != nullptr) {
        count++;
    }

    jclass stringClass = env->FindClass("java/lang/String");
    jclass stringArrayClass = env->FindClass("[Ljava/lang/String;");

    jobjectArray result = env->NewObjectArray(count, stringArrayClass, nullptr);

    for (size_t i = 0; i < count; i++) {
        jobjectArray element = env->NewObjectArray(2, stringClass, nullptr);
        jstring symbolFileName = env->NewStringUTF(kFileContents[i].symbol_file_name);
        jstring content = env->NewStringUTF(kFileContents[i].content);

        env->SetObjectArrayElement(element, 0, symbolFileName);
        env->SetObjectArrayElement(element, 1, content);

        env->SetObjectArrayElement(result, i, element);

        env->DeleteLocalRef(symbolFileName);
        env->DeleteLocalRef(content);
        env->DeleteLocalRef(element);
    }

    return result;
}
