/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.android.os.cts.multiuser.messaging;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Action {
    public static final String REGEX = "\\{name:(.*?),process:(" + ProcessInfo.REGEX + ")\\}";
    public static final Pattern PARSE_PATTERN = Pattern.compile(REGEX);
    private final String mName;
    private final ProcessInfo mProcessInfo;

    public Action(String name, ProcessInfo processInfo) {
        this.mName = name;
        this.mProcessInfo = processInfo;
    }

    public String getName() {
        return mName;
    }

    public ProcessInfo getProcessInfo() {
        return mProcessInfo;
    }

    /**
     * Constructor to deserialize from the custom string FORMAT.
     *
     * @param actionString String generated by the toString() method.
     * @throws IllegalArgumentException if the string doesn't match the expected FORMAT.
     */
    public Action(String actionString) {
        if (actionString == null) {
            throw new IllegalArgumentException("Input string cannot be null");
        }
        Matcher matcher = PARSE_PATTERN.matcher(actionString);
        if (matcher.matches()) {
            try {
                this.mName = matcher.group(1);
                this.mProcessInfo = new ProcessInfo(matcher.group(2));
            } catch (NumberFormatException e) {
                throw new IllegalArgumentException(
                        "Failed to parse integer values from string: " + actionString, e);
            }
        } else {
            throw new IllegalArgumentException(
                    "String does not match Action FORMAT: " + actionString);
        }
    }

    /**
     * Helper method to compare results of different actions
     *
     * @param other - other Action to compare
     * @param withName - if false name will not be compared
     * @return true if Actions are equals
     */
    public boolean compare(Action other, boolean withName) {
        return (this.getName().equals(other.getName()) || !withName)
                && this.getProcessInfo().compare(other.getProcessInfo());
    }

    @Override
    public String toString() {
        return String.format("{name:%s,process:%s}", mName, mProcessInfo);
    }
}
