/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.android.os.cts.multiuser.messaging;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class ProcessInfo {
    public static final String REGEX =
            "\\{name:(.*?),uid:(\\d+),userHandle:UserHandle\\{(\\d+)\\},targetUserId:(\\d+)\\}";
    public static final Pattern PARSE_PATTERN = Pattern.compile(REGEX);
    private final String mName;
    private final int mUid;
    private final String mUserHandle;
    private final int mTargetUserId;

    public ProcessInfo(String name, int uid, String userHandle, int targetUserId) {
        this.mName = name;
        this.mUid = uid;
        this.mUserHandle = userHandle;
        this.mTargetUserId = targetUserId;
    }

    public String getName() {
        return mName;
    }

    public int getUid() {
        return mUid;
    }

    public String getUserHandle() {
        return mUserHandle;
    }

    public int getTargetUserId() {
        return mTargetUserId;
    }

    /**
     * Constructor to deserialize from the custom string FORMAT.
     *
     * @param processInfoString String generated by the toString() method.
     * @throws IllegalArgumentException if the string doesn't match the expected FORMAT.
     */
    public ProcessInfo(String processInfoString) {
        if (processInfoString == null) {
            throw new IllegalArgumentException("Input string cannot be null");
        }

        Matcher matcher = PARSE_PATTERN.matcher(processInfoString);
        if (matcher.matches()) {
            try {
                this.mName = matcher.group(1);
                this.mUid = Integer.parseInt(matcher.group(2));
                this.mUserHandle = "UserHandle{" + Integer.parseInt(matcher.group(3)) + "}";
                this.mTargetUserId = Integer.parseInt(matcher.group(4));
            } catch (NumberFormatException e) {
                throw new IllegalArgumentException(
                        "Failed to parse integer values from string: " + processInfoString, e);
            }
        } else {
            throw new IllegalArgumentException(
                    "String does not match ProcessInfo FORMAT: " + processInfoString);
        }
    }

    /**
     * Helper method to compare results of different actions
     *
     * @param other - other ProcessInfo to compare
     * @return true if ProcessInfo are equals
     */
    public boolean compare(ProcessInfo other) {
        return this.getName().equals(other.getName())
                && this.getUid() == other.getUid()
                && this.getUserHandle().equals(other.getUserHandle())
                && this.getTargetUserId() == other.getTargetUserId();
    }

    @Override
    public String toString() {
        return String.format(
                "{name:%s,uid:%d,userHandle:%s,targetUserId:%d}",
                mName, mUid, mUserHandle, mTargetUserId);
    }
}
