/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.devicepolicy.cts

import android.app.admin.PolicyIdentifier
import android.app.admin.flags.Flags
import com.android.bedstead.enterprise.annotations.EnterprisePolicy
import com.android.bedstead.enterprise.annotations.EnterprisePolicy.APPLIED_BY_DEVICE_OWNER
import com.android.bedstead.enterprise.annotations.EnterprisePolicy.APPLIED_BY_ORGANIZATION_OWNED_PROFILE_OWNER_PROFILE
import com.android.bedstead.enterprise.annotations.EnterprisePolicy.APPLIES_GLOBALLY
import com.android.bedstead.enterprise.annotations.EnterprisePolicy.Permission
import com.android.bedstead.enterprise.annotations.UsesEnterprisePolicies
import com.android.bedstead.flags.annotations.RequireFlagsEnabled
import com.android.bedstead.harrier.BedsteadJUnit4
import com.android.compatibility.common.util.ApiTest
import org.junit.runner.RunWith

// Policy definition that runs with POLICY_SCOPE_USER.
// Generated by running `cts-policy-tests-generator LOCKSCREEN_MESSAGE`.
@EnterprisePolicy(
    dpc = [],
    permissions = []
)
public final class LockscreenMessagePolicyScopeUser

// Policy definition that runs with POLICY_SCOPE_DEVICE.
// Generated by running `cts-policy-tests-generator LOCKSCREEN_MESSAGE`.
@EnterprisePolicy(
    dpc =
        [
            APPLIED_BY_DEVICE_OWNER or APPLIES_GLOBALLY,
            APPLIED_BY_ORGANIZATION_OWNED_PROFILE_OWNER_PROFILE or APPLIES_GLOBALLY,
        ],
    permissions =
        [
            Permission(
                appliedWith =
                    [
                        "android.permission.MANAGE_DEVICE_POLICY_LOCKSCREEN_INFO",
                        "android.permission.MANAGE_DEVICE_POLICY_ACROSS_USERS",
                    ],
                appliesTo = APPLIES_GLOBALLY,
            ),
        ]
)
public final class LockscreenMessagePolicyScopeDevice

// Policy definition that runs with POLICY_SCOPE_PARENT_USER.
// Generated by running `cts-policy-tests-generator LOCKSCREEN_MESSAGE`.
@EnterprisePolicy(
    dpc = [],
    permissions = []
)
public final class LockscreenMessagePolicyScopeParentUser

@RunWith(BedsteadJUnit4::class)
@RequireFlagsEnabled(Flags.FLAG_POLICY_STREAMLINING, Flags.FLAG_POLICY_STREAMLINING_TESTS)
@UsesEnterprisePolicies(
    scopeUser = LockscreenMessagePolicyScopeUser::class,
    scopeDevice = LockscreenMessagePolicyScopeDevice::class,
    scopeParentUser = LockscreenMessagePolicyScopeParentUser::class,
)
@ApiTest(
    apis =
        [
            "android.app.admin.PolicyIdentifier#LOCKSCREEN_MESSAGE",
        ]
)
class LockscreenMessageTest : CommonPolicyTests<String>() {

    override val policyIdentifier = PolicyIdentifier.LOCKSCREEN_MESSAGE

    override val validValues =
        listOf(
            "Normal test message",
            String(CharArray(256) { 'A' }), // A longer string
            " ", // Whitespace only input should work
            "\t",
            "Test smiley unicode: \uD83D\uDE00",
            "Test \u0000 null"
        )

    override val invalidValueTestCases =
        listOf(
            InvalidValueTestCase("", expectedError = "Empty string is not allowed"),
        )

    override fun scopeDevice_setValueToDefault_accepted() {
        // TODO: b/476973331 - Support nullable strings in Bedstead.
    }
}
