/*
* Copyright 2025 The Android Open Source Project
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package com.android.cts.deviceinfo;

import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

/**
 *
 * This class converts vkjson names to DeviceInfo names
 *
 * VkJSON uses the original Vulkan field names, while VulkanDeviceInfo follows the DeviceInfo
 * naming convention. So VkJSON fields named like "sparseProperties" will be converted to names
 * like "sparse_properties".
 *
 */
public final class VulkanDeviceInfoUtils {

    public static final String KEY_ALPHA_TO_ONE = "alphaToOne";
    public static final String KEY_API_VERSION = "apiVersion";
    public static final String KEY_BIT16_STORAGE_FEATURES = "bit16StorageFeatures";
    public static final String KEY_BIT8_STORAGE_FEATURES_KHR = "bit8StorageFeaturesKHR";
    public static final String KEY_BLOCK_TEXEL_VIEW_COMPATIBLE_MULTIPLE_LAYERS = "blockTexelViewCompatibleMultipleLayers";
    public static final String KEY_BRESENHAM_LINES = "bresenhamLines";
    public static final String KEY_BUFFER_DEVICE_ADDRESS = "bufferDeviceAddress";
    public static final String KEY_BUFFER_DEVICE_ADDRESS_CAPTURE_REPLAY = "bufferDeviceAddressCaptureReplay";
    public static final String KEY_BUFFER_DEVICE_ADDRESS_MULTI_DEVICE = "bufferDeviceAddressMultiDevice";
    public static final String KEY_BUFFER_FEATURES = "bufferFeatures";
    public static final String KEY_BUFFER_IMAGE_GRANULARITY = "bufferImageGranularity";
    public static final String KEY_COMPATIBLE_HANDLE_TYPES = "compatibleHandleTypes";
    public static final String KEY_COMPUTE_FULL_SUBGROUPS = "computeFullSubgroups";
    public static final String KEY_CONFORMANCE_VERSION = "conformanceVersion";
    public static final String KEY_COPY_DST_LAYOUT_COUNT = "copyDstLayoutCount";
    public static final String KEY_COPY_SRC_LAYOUT_COUNT = "copySrcLayoutCount";
    public static final String KEY_CORE11 = "core11";
    public static final String KEY_CORE12 = "core12";
    public static final String KEY_CORE13 = "core13";
    public static final String KEY_CORE14 = "core14";
    public static final String KEY_CUSTOM_BORDER_COLORS = "customBorderColors";
    public static final String KEY_CUSTOM_BORDER_COLOR_FEATURES_EXT = "customBorderColorFeaturesEXT";
    public static final String KEY_CUSTOM_BORDER_COLOR_WITHOUT_FORMAT = "customBorderColorWithoutFormat";
    public static final String KEY_DEFAULT_ROBUSTNESS_IMAGES = "defaultRobustnessImages";
    public static final String KEY_DEFAULT_ROBUSTNESS_STORAGE_BUFFERS = "defaultRobustnessStorageBuffers";
    public static final String KEY_DEFAULT_ROBUSTNESS_UNIFORM_BUFFERS = "defaultRobustnessUniformBuffers";
    public static final String KEY_DEFAULT_ROBUSTNESS_VERTEX_INPUTS = "defaultRobustnessVertexInputs";
    public static final String KEY_DENORM_BEHAVIOR_INDEPENDENCE = "denormBehaviorIndependence";
    public static final String KEY_DEPTH = "depth";
    public static final String KEY_DEPTH_BIAS_CLAMP = "depthBiasClamp";
    public static final String KEY_DEPTH_BOUNDS = "depthBounds";
    public static final String KEY_DEPTH_CLAMP = "depthClamp";
    public static final String KEY_DEPTH_STENCIL_SWIZZLE_ONE_SUPPORT = "depthStencilSwizzleOneSupport";
    public static final String KEY_DESCRIPTION = "description";
    public static final String KEY_DESCRIPTOR_BINDING_INLINE_UNIFORM_BLOCK_UPDATE_AFTER_BIND = "descriptorBindingInlineUniformBlockUpdateAfterBind";
    public static final String KEY_DESCRIPTOR_BINDING_PARTIALLY_BOUND = "descriptorBindingPartiallyBound";
    public static final String KEY_DESCRIPTOR_BINDING_SAMPLED_IMAGE_UPDATE_AFTER_BIND = "descriptorBindingSampledImageUpdateAfterBind";
    public static final String KEY_DESCRIPTOR_BINDING_STORAGE_BUFFER_UPDATE_AFTER_BIND = "descriptorBindingStorageBufferUpdateAfterBind";
    public static final String KEY_DESCRIPTOR_BINDING_STORAGE_IMAGE_UPDATE_AFTER_BIND = "descriptorBindingStorageImageUpdateAfterBind";
    public static final String KEY_DESCRIPTOR_BINDING_STORAGE_TEXEL_BUFFER_UPDATE_AFTER_BIND = "descriptorBindingStorageTexelBufferUpdateAfterBind";
    public static final String KEY_DESCRIPTOR_BINDING_UNIFORM_BUFFER_UPDATE_AFTER_BIND = "descriptorBindingUniformBufferUpdateAfterBind";
    public static final String KEY_DESCRIPTOR_BINDING_UNIFORM_TEXEL_BUFFER_UPDATE_AFTER_BIND = "descriptorBindingUniformTexelBufferUpdateAfterBind";
    public static final String KEY_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING = "descriptorBindingUpdateUnusedWhilePending";
    public static final String KEY_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT = "descriptorBindingVariableDescriptorCount";
    public static final String KEY_DESCRIPTOR_INDEXING = "descriptorIndexing";
    public static final String KEY_DEVICES = "devices";
    public static final String KEY_DEVICE_GROUPS = "deviceGroups";
    public static final String KEY_DEVICE_ID = "deviceID";
    public static final String KEY_DEVICE_LUID = "deviceLUID";
    public static final String KEY_DEVICE_LUID_VALID = "deviceLUIDValid";
    public static final String KEY_DEVICE_NAME = "deviceName";
    public static final String KEY_DEVICE_NODE_MASK = "deviceNodeMask";
    public static final String KEY_DEVICE_TYPE = "deviceType";
    public static final String KEY_DEVICE_UUID = "deviceUUID";
    public static final String KEY_DISCRETE_QUEUE_PRIORITIES = "discreteQueuePriorities";
    public static final String KEY_DRAW_INDIRECT_COUNT = "drawIndirectCount";
    public static final String KEY_DRAW_INDIRECT_FIRST_INSTANCE = "drawIndirectFirstInstance";
    public static final String KEY_DRIVER_ID = "driverID";
    public static final String KEY_DRIVER_INFO = "driverInfo";
    public static final String KEY_DRIVER_NAME = "driverName";
    public static final String KEY_DRIVER_PROPERTIES_KHR = "driverPropertiesKHR";
    public static final String KEY_DRIVER_UUID = "driverUUID";
    public static final String KEY_DRIVER_VERSION = "driverVersion";
    public static final String KEY_DUAL_SRC_BLEND = "dualSrcBlend";
    public static final String KEY_DYNAMIC_RENDERING = "dynamicRendering";
    public static final String KEY_DYNAMIC_RENDERING_LOCAL_READ = "dynamicRenderingLocalRead";
    public static final String KEY_DYNAMIC_RENDERING_LOCAL_READ_DEPTH_STENCIL_ATTACHMENTS = "dynamicRenderingLocalReadDepthStencilAttachments";
    public static final String KEY_DYNAMIC_RENDERING_LOCAL_READ_MULTISAMPLED_ATTACHMENTS = "dynamicRenderingLocalReadMultisampledAttachments";
    public static final String KEY_EARLY_FRAGMENT_MULTISAMPLE_COVERAGE_AFTER_SAMPLE_COUNTING = "earlyFragmentMultisampleCoverageAfterSampleCounting";
    public static final String KEY_EARLY_FRAGMENT_SAMPLE_MASK_TEST_BEFORE_SAMPLE_COUNTING = "earlyFragmentSampleMaskTestBeforeSampleCounting";
    public static final String KEY_EXPORT_FROM_IMPORTED_HANDLE_TYPES = "exportFromImportedHandleTypes";
    public static final String KEY_EXTENSIONS = "extensions";
    public static final String KEY_EXTENSION_NAME = "extensionName";
    public static final String KEY_EXTERNAL_FENCE_FEATURES = "externalFenceFeatures";
    public static final String KEY_EXTERNAL_FENCE_PROPERTIES = "externalFenceProperties";
    public static final String KEY_EXTERNAL_SEMAPHORE_FEATURES = "externalSemaphoreFeatures";
    public static final String KEY_EXTERNAL_SEMAPHORE_PROPERTIES = "externalSemaphoreProperties";
    public static final String KEY_FEATURES = "features";
    public static final String KEY_FILL_MODE_NON_SOLID = "fillModeNonSolid";
    public static final String KEY_FILTER_MINMAX_IMAGE_COMPONENT_MAPPING = "filterMinmaxImageComponentMapping";
    public static final String KEY_FILTER_MINMAX_SINGLE_COMPONENT_FORMATS = "filterMinmaxSingleComponentFormats";
    public static final String KEY_FLAGS = "flags";
    public static final String KEY_FLOAT16_INT8_FEATURES_KHR = "float16Int8FeaturesKHR";
    public static final String KEY_FLOAT_CONTROLS_PROPERTIES_KHR = "floatControlsPropertiesKHR";
    public static final String KEY_FORMATS = "formats";
    public static final String KEY_FRAGMENT_SHADING_RATE_CLAMP_COMBINER_INPUTS = "fragmentShadingRateClampCombinerInputs";
    public static final String KEY_FRAGMENT_STORES_AND_ATOMICS = "fragmentStoresAndAtomics";
    public static final String KEY_FRAMEBUFFER_COLOR_SAMPLE_COUNTS = "framebufferColorSampleCounts";
    public static final String KEY_FRAMEBUFFER_DEPTH_SAMPLE_COUNTS = "framebufferDepthSampleCounts";
    public static final String KEY_FRAMEBUFFER_INTEGER_COLOR_SAMPLE_COUNTS = "framebufferIntegerColorSampleCounts";
    public static final String KEY_FRAMEBUFFER_NO_ATTACHMENTS_SAMPLE_COUNTS = "framebufferNoAttachmentsSampleCounts";
    public static final String KEY_FRAMEBUFFER_STENCIL_SAMPLE_COUNTS = "framebufferStencilSampleCounts";
    public static final String KEY_FULL_DRAW_INDEX_UINT32 = "fullDrawIndexUint32";
    public static final String KEY_GEOMETRY_SHADER = "geometryShader";
    public static final String KEY_GEOMETRY_STREAMS = "geometryStreams";
    public static final String KEY_GLOBAL_PRIORITY_QUERY = "globalPriorityQuery";
    public static final String KEY_HEAP_INDEX = "heapIndex";
    public static final String KEY_HEIGHT = "height";
    public static final String KEY_HOST_IMAGE_COPY = "hostImageCopy";
    public static final String KEY_HOST_QUERY_RESET = "hostQueryReset";
    public static final String KEY_IDENTICAL_MEMORY_TYPE_REQUIREMENTS = "identicalMemoryTypeRequirements";
    public static final String KEY_ID_PROPERTIES = "idProperties";
    public static final String KEY_IMAGELESS_FRAMEBUFFER = "imagelessFramebuffer";
    public static final String KEY_IMAGE_2D_VIEW_OF_3D = "image2DViewOf3D";
    public static final String KEY_IMAGE_2D_VIEW_OF_3D_FEATURES_EXT = "image2DViewOf3DFeaturesEXT";
    public static final String KEY_IMAGE_CUBE_ARRAY = "imageCubeArray";
    public static final String KEY_IMPLEMENTATION_VERSION = "implementationVersion";
    public static final String KEY_INDEPENDENT_BLEND = "independentBlend";
    public static final String KEY_INDEPENDENT_RESOLVE = "independentResolve";
    public static final String KEY_INDEPENDENT_RESOLVE_NONE = "independentResolveNone";
    public static final String KEY_INDEX_TYPE_UINT8 = "indexTypeUint8";
    public static final String KEY_INDEX_TYPE_UINT8_FEATURES_EXT = "indexTypeUint8FeaturesEXT";
    public static final String KEY_INDEX_TYPE_UINT8_FEATURES_KHR = "indexTypeUint8FeaturesKHR";
    public static final String KEY_INHERITED_QUERIES = "inheritedQueries";
    public static final String KEY_INLINE_UNIFORM_BLOCK = "inlineUniformBlock";
    public static final String KEY_INSTANCE_API_VERSION = "instanceApiVersion";
    public static final String KEY_INTEGER_DOT_PRODUCT_16BIT_MIXED_SIGNEDNESS_ACCELERATED = "integerDotProduct16BitMixedSignednessAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_16BIT_SIGNED_ACCELERATED = "integerDotProduct16BitSignedAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_16BIT_UNSIGNED_ACCELERATED = "integerDotProduct16BitUnsignedAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_32BIT_MIXED_SIGNEDNESS_ACCELERATED = "integerDotProduct32BitMixedSignednessAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_32BIT_SIGNED_ACCELERATED = "integerDotProduct32BitSignedAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_32BIT_UNSIGNED_ACCELERATED = "integerDotProduct32BitUnsignedAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_4X8BIT_PACKED_MIXED_SIGNEDNESS_ACCELERATED = "integerDotProduct4x8BitPackedMixedSignednessAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_4X8BIT_PACKED_SIGNED_ACCELERATED = "integerDotProduct4x8BitPackedSignedAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_4X8BIT_PACKED_UNSIGNED_ACCELERATED = "integerDotProduct4x8BitPackedUnsignedAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_64BIT_MIXED_SIGNEDNESS_ACCELERATED = "integerDotProduct64BitMixedSignednessAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_64BIT_SIGNED_ACCELERATED = "integerDotProduct64BitSignedAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_64BIT_UNSIGNED_ACCELERATED = "integerDotProduct64BitUnsignedAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_8BIT_MIXED_SIGNEDNESS_ACCELERATED = "integerDotProduct8BitMixedSignednessAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_8BIT_SIGNED_ACCELERATED = "integerDotProduct8BitSignedAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_8BIT_UNSIGNED_ACCELERATED = "integerDotProduct8BitUnsignedAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_ACCUMULATING_SATURATING_16BIT_MIXED_SIGNEDNESS_ACCELERATED = "integerDotProductAccumulatingSaturating16BitMixedSignednessAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_ACCUMULATING_SATURATING_16BIT_SIGNED_ACCELERATED = "integerDotProductAccumulatingSaturating16BitSignedAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_ACCUMULATING_SATURATING_16BIT_UNSIGNED_ACCELERATED = "integerDotProductAccumulatingSaturating16BitUnsignedAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_ACCUMULATING_SATURATING_32BIT_MIXED_SIGNEDNESS_ACCELERATED = "integerDotProductAccumulatingSaturating32BitMixedSignednessAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_ACCUMULATING_SATURATING_32BIT_SIGNED_ACCELERATED = "integerDotProductAccumulatingSaturating32BitSignedAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_ACCUMULATING_SATURATING_32BIT_UNSIGNED_ACCELERATED = "integerDotProductAccumulatingSaturating32BitUnsignedAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_ACCUMULATING_SATURATING_4X8BIT_PACKED_MIXED_SIGNEDNESS_ACCELERATED = "integerDotProductAccumulatingSaturating4x8BitPackedMixedSignednessAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_ACCUMULATING_SATURATING_4X8BIT_PACKED_SIGNED_ACCELERATED = "integerDotProductAccumulatingSaturating4x8BitPackedSignedAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_ACCUMULATING_SATURATING_4X8BIT_PACKED_UNSIGNED_ACCELERATED = "integerDotProductAccumulatingSaturating4x8BitPackedUnsignedAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_ACCUMULATING_SATURATING_64BIT_MIXED_SIGNEDNESS_ACCELERATED = "integerDotProductAccumulatingSaturating64BitMixedSignednessAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_ACCUMULATING_SATURATING_64BIT_SIGNED_ACCELERATED = "integerDotProductAccumulatingSaturating64BitSignedAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_ACCUMULATING_SATURATING_64BIT_UNSIGNED_ACCELERATED = "integerDotProductAccumulatingSaturating64BitUnsignedAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_ACCUMULATING_SATURATING_8BIT_MIXED_SIGNEDNESS_ACCELERATED = "integerDotProductAccumulatingSaturating8BitMixedSignednessAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_ACCUMULATING_SATURATING_8BIT_SIGNED_ACCELERATED = "integerDotProductAccumulatingSaturating8BitSignedAccelerated";
    public static final String KEY_INTEGER_DOT_PRODUCT_ACCUMULATING_SATURATING_8BIT_UNSIGNED_ACCELERATED = "integerDotProductAccumulatingSaturating8BitUnsignedAccelerated";
    public static final String KEY_LARGE_POINTS = "largePoints";
    public static final String KEY_LAYERS = "layers";
    public static final String KEY_LAYER_NAME = "layerName";
    public static final String KEY_LIMITS = "limits";
    public static final String KEY_LINEAR_TILING_FEATURES = "linearTilingFeatures";
    public static final String KEY_LINE_RASTERIZATION_FEATURES_EXT = "lineRasterizationFeaturesEXT";
    public static final String KEY_LINE_SUB_PIXEL_PRECISION_BITS = "lineSubPixelPrecisionBits";
    public static final String KEY_LINE_WIDTH_GRANULARITY = "lineWidthGranularity";
    public static final String KEY_LINE_WIDTH_RANGE = "lineWidthRange";
    public static final String KEY_LOGIC_OP = "logicOp";
    public static final String KEY_MAINTENANCE4 = "maintenance4";
    public static final String KEY_MAINTENANCE5 = "maintenance5";
    public static final String KEY_MAINTENANCE6 = "maintenance6";
    public static final String KEY_MAINTENANCE_3_PROPERTIES = "maintenance3Properties";
    public static final String KEY_MAJOR = "major";
    public static final String KEY_MAX_BOUND_DESCRIPTOR_SETS = "maxBoundDescriptorSets";
    public static final String KEY_MAX_BUFFER_SIZE = "maxBufferSize";
    public static final String KEY_MAX_CLIP_DISTANCES = "maxClipDistances";
    public static final String KEY_MAX_COLOR_ATTACHMENTS = "maxColorAttachments";
    public static final String KEY_MAX_COMBINED_CLIP_AND_CULL_DISTANCES = "maxCombinedClipAndCullDistances";
    public static final String KEY_MAX_COMBINED_IMAGE_SAMPLER_DESCRIPTOR_COUNT = "maxCombinedImageSamplerDescriptorCount";
    public static final String KEY_MAX_COMPUTE_SHARED_MEMORY_SIZE = "maxComputeSharedMemorySize";
    public static final String KEY_MAX_COMPUTE_WORKGROUP_SUBGROUPS = "maxComputeWorkgroupSubgroups";
    public static final String KEY_MAX_COMPUTE_WORK_GROUP_COUNT = "maxComputeWorkGroupCount";
    public static final String KEY_MAX_COMPUTE_WORK_GROUP_INVOCATIONS = "maxComputeWorkGroupInvocations";
    public static final String KEY_MAX_COMPUTE_WORK_GROUP_SIZE = "maxComputeWorkGroupSize";
    public static final String KEY_MAX_CULL_DISTANCES = "maxCullDistances";
    public static final String KEY_MAX_DESCRIPTOR_SET_INLINE_UNIFORM_BLOCKS = "maxDescriptorSetInlineUniformBlocks";
    public static final String KEY_MAX_DESCRIPTOR_SET_INPUT_ATTACHMENTS = "maxDescriptorSetInputAttachments";
    public static final String KEY_MAX_DESCRIPTOR_SET_SAMPLED_IMAGES = "maxDescriptorSetSampledImages";
    public static final String KEY_MAX_DESCRIPTOR_SET_SAMPLERS = "maxDescriptorSetSamplers";
    public static final String KEY_MAX_DESCRIPTOR_SET_STORAGE_BUFFERS = "maxDescriptorSetStorageBuffers";
    public static final String KEY_MAX_DESCRIPTOR_SET_STORAGE_BUFFERS_DYNAMIC = "maxDescriptorSetStorageBuffersDynamic";
    public static final String KEY_MAX_DESCRIPTOR_SET_STORAGE_IMAGES = "maxDescriptorSetStorageImages";
    public static final String KEY_MAX_DESCRIPTOR_SET_UNIFORM_BUFFERS = "maxDescriptorSetUniformBuffers";
    public static final String KEY_MAX_DESCRIPTOR_SET_UNIFORM_BUFFERS_DYNAMIC = "maxDescriptorSetUniformBuffersDynamic";
    public static final String KEY_MAX_DESCRIPTOR_SET_UPDATE_AFTER_BIND_INLINE_UNIFORM_BLOCKS = "maxDescriptorSetUpdateAfterBindInlineUniformBlocks";
    public static final String KEY_MAX_DESCRIPTOR_SET_UPDATE_AFTER_BIND_INPUT_ATTACHMENTS = "maxDescriptorSetUpdateAfterBindInputAttachments";
    public static final String KEY_MAX_DESCRIPTOR_SET_UPDATE_AFTER_BIND_SAMPLED_IMAGES = "maxDescriptorSetUpdateAfterBindSampledImages";
    public static final String KEY_MAX_DESCRIPTOR_SET_UPDATE_AFTER_BIND_SAMPLERS = "maxDescriptorSetUpdateAfterBindSamplers";
    public static final String KEY_MAX_DESCRIPTOR_SET_UPDATE_AFTER_BIND_STORAGE_BUFFERS = "maxDescriptorSetUpdateAfterBindStorageBuffers";
    public static final String KEY_MAX_DESCRIPTOR_SET_UPDATE_AFTER_BIND_STORAGE_BUFFERS_DYNAMIC = "maxDescriptorSetUpdateAfterBindStorageBuffersDynamic";
    public static final String KEY_MAX_DESCRIPTOR_SET_UPDATE_AFTER_BIND_STORAGE_IMAGES = "maxDescriptorSetUpdateAfterBindStorageImages";
    public static final String KEY_MAX_DESCRIPTOR_SET_UPDATE_AFTER_BIND_UNIFORM_BUFFERS = "maxDescriptorSetUpdateAfterBindUniformBuffers";
    public static final String KEY_MAX_DESCRIPTOR_SET_UPDATE_AFTER_BIND_UNIFORM_BUFFERS_DYNAMIC = "maxDescriptorSetUpdateAfterBindUniformBuffersDynamic";
    public static final String KEY_MAX_DRAW_INDEXED_INDEX_VALUE = "maxDrawIndexedIndexValue";
    public static final String KEY_MAX_DRAW_INDIRECT_COUNT = "maxDrawIndirectCount";
    public static final String KEY_MAX_FRAGMENT_COMBINED_OUTPUT_RESOURCES = "maxFragmentCombinedOutputResources";
    public static final String KEY_MAX_FRAGMENT_DUAL_SRC_ATTACHMENTS = "maxFragmentDualSrcAttachments";
    public static final String KEY_MAX_FRAGMENT_INPUT_COMPONENTS = "maxFragmentInputComponents";
    public static final String KEY_MAX_FRAGMENT_OUTPUT_ATTACHMENTS = "maxFragmentOutputAttachments";
    public static final String KEY_MAX_FRAMEBUFFER_HEIGHT = "maxFramebufferHeight";
    public static final String KEY_MAX_FRAMEBUFFER_LAYERS = "maxFramebufferLayers";
    public static final String KEY_MAX_FRAMEBUFFER_WIDTH = "maxFramebufferWidth";
    public static final String KEY_MAX_GEOMETRY_INPUT_COMPONENTS = "maxGeometryInputComponents";
    public static final String KEY_MAX_GEOMETRY_OUTPUT_COMPONENTS = "maxGeometryOutputComponents";
    public static final String KEY_MAX_GEOMETRY_OUTPUT_VERTICES = "maxGeometryOutputVertices";
    public static final String KEY_MAX_GEOMETRY_SHADER_INVOCATIONS = "maxGeometryShaderInvocations";
    public static final String KEY_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS = "maxGeometryTotalOutputComponents";
    public static final String KEY_MAX_IMAGE_ARRAY_LAYERS = "maxImageArrayLayers";
    public static final String KEY_MAX_IMAGE_DIMENSION_1D = "maxImageDimension1D";
    public static final String KEY_MAX_IMAGE_DIMENSION_2D = "maxImageDimension2D";
    public static final String KEY_MAX_IMAGE_DIMENSION_3D = "maxImageDimension3D";
    public static final String KEY_MAX_IMAGE_DIMENSION_CUBE = "maxImageDimensionCube";
    public static final String KEY_MAX_INLINE_UNIFORM_BLOCK_SIZE = "maxInlineUniformBlockSize";
    public static final String KEY_MAX_INLINE_UNIFORM_TOTAL_SIZE = "maxInlineUniformTotalSize";
    public static final String KEY_MAX_INTERPOLATION_OFFSET = "maxInterpolationOffset";
    public static final String KEY_MAX_MEMORY_ALLOCATION_COUNT = "maxMemoryAllocationCount";
    public static final String KEY_MAX_MEMORY_ALLOCATION_SIZE = "maxMemoryAllocationSize";
    public static final String KEY_MAX_MULTIVIEW_INSTANCE_INDEX = "maxMultiviewInstanceIndex";
    public static final String KEY_MAX_MULTIVIEW_VIEW_COUNT = "maxMultiviewViewCount";
    public static final String KEY_MAX_PER_SET_DESCRIPTORS = "maxPerSetDescriptors";
    public static final String KEY_MAX_PER_STAGE_DESCRIPTOR_INLINE_UNIFORM_BLOCKS = "maxPerStageDescriptorInlineUniformBlocks";
    public static final String KEY_MAX_PER_STAGE_DESCRIPTOR_INPUT_ATTACHMENTS = "maxPerStageDescriptorInputAttachments";
    public static final String KEY_MAX_PER_STAGE_DESCRIPTOR_SAMPLED_IMAGES = "maxPerStageDescriptorSampledImages";
    public static final String KEY_MAX_PER_STAGE_DESCRIPTOR_SAMPLERS = "maxPerStageDescriptorSamplers";
    public static final String KEY_MAX_PER_STAGE_DESCRIPTOR_STORAGE_BUFFERS = "maxPerStageDescriptorStorageBuffers";
    public static final String KEY_MAX_PER_STAGE_DESCRIPTOR_STORAGE_IMAGES = "maxPerStageDescriptorStorageImages";
    public static final String KEY_MAX_PER_STAGE_DESCRIPTOR_UNIFORM_BUFFERS = "maxPerStageDescriptorUniformBuffers";
    public static final String KEY_MAX_PER_STAGE_DESCRIPTOR_UPDATE_AFTER_BIND_INLINE_UNIFORM_BLOCKS = "maxPerStageDescriptorUpdateAfterBindInlineUniformBlocks";
    public static final String KEY_MAX_PER_STAGE_DESCRIPTOR_UPDATE_AFTER_BIND_INPUT_ATTACHMENTS = "maxPerStageDescriptorUpdateAfterBindInputAttachments";
    public static final String KEY_MAX_PER_STAGE_DESCRIPTOR_UPDATE_AFTER_BIND_SAMPLED_IMAGES = "maxPerStageDescriptorUpdateAfterBindSampledImages";
    public static final String KEY_MAX_PER_STAGE_DESCRIPTOR_UPDATE_AFTER_BIND_SAMPLERS = "maxPerStageDescriptorUpdateAfterBindSamplers";
    public static final String KEY_MAX_PER_STAGE_DESCRIPTOR_UPDATE_AFTER_BIND_STORAGE_BUFFERS = "maxPerStageDescriptorUpdateAfterBindStorageBuffers";
    public static final String KEY_MAX_PER_STAGE_DESCRIPTOR_UPDATE_AFTER_BIND_STORAGE_IMAGES = "maxPerStageDescriptorUpdateAfterBindStorageImages";
    public static final String KEY_MAX_PER_STAGE_DESCRIPTOR_UPDATE_AFTER_BIND_UNIFORM_BUFFERS = "maxPerStageDescriptorUpdateAfterBindUniformBuffers";
    public static final String KEY_MAX_PER_STAGE_RESOURCES = "maxPerStageResources";
    public static final String KEY_MAX_PER_STAGE_UPDATE_AFTER_BIND_RESOURCES = "maxPerStageUpdateAfterBindResources";
    public static final String KEY_MAX_PUSH_CONSTANTS_SIZE = "maxPushConstantsSize";
    public static final String KEY_MAX_PUSH_DESCRIPTORS = "maxPushDescriptors";
    public static final String KEY_MAX_SAMPLER_ALLOCATION_COUNT = "maxSamplerAllocationCount";
    public static final String KEY_MAX_SAMPLER_ANISOTROPY = "maxSamplerAnisotropy";
    public static final String KEY_MAX_SAMPLER_LOD_BIAS = "maxSamplerLodBias";
    public static final String KEY_MAX_SAMPLE_MASK_WORDS = "maxSampleMaskWords";
    public static final String KEY_MAX_STORAGE_BUFFER_RANGE = "maxStorageBufferRange";
    public static final String KEY_MAX_SUBGROUP_SIZE = "maxSubgroupSize";
    public static final String KEY_MAX_TESSELLATION_CONTROL_PER_PATCH_OUTPUT_COMPONENTS = "maxTessellationControlPerPatchOutputComponents";
    public static final String KEY_MAX_TESSELLATION_CONTROL_PER_VERTEX_INPUT_COMPONENTS = "maxTessellationControlPerVertexInputComponents";
    public static final String KEY_MAX_TESSELLATION_CONTROL_PER_VERTEX_OUTPUT_COMPONENTS = "maxTessellationControlPerVertexOutputComponents";
    public static final String KEY_MAX_TESSELLATION_CONTROL_TOTAL_OUTPUT_COMPONENTS = "maxTessellationControlTotalOutputComponents";
    public static final String KEY_MAX_TESSELLATION_EVALUATION_INPUT_COMPONENTS = "maxTessellationEvaluationInputComponents";
    public static final String KEY_MAX_TESSELLATION_EVALUATION_OUTPUT_COMPONENTS = "maxTessellationEvaluationOutputComponents";
    public static final String KEY_MAX_TESSELLATION_GENERATION_LEVEL = "maxTessellationGenerationLevel";
    public static final String KEY_MAX_TESSELLATION_PATCH_SIZE = "maxTessellationPatchSize";
    public static final String KEY_MAX_TEXEL_BUFFER_ELEMENTS = "maxTexelBufferElements";
    public static final String KEY_MAX_TEXEL_GATHER_OFFSET = "maxTexelGatherOffset";
    public static final String KEY_MAX_TEXEL_OFFSET = "maxTexelOffset";
    public static final String KEY_MAX_TIMELINE_SEMAPHORE_VALUE_DIFFERENCE = "maxTimelineSemaphoreValueDifference";
    public static final String KEY_MAX_UNIFORM_BUFFER_RANGE = "maxUniformBufferRange";
    public static final String KEY_MAX_UPDATE_AFTER_BIND_DESCRIPTORS_IN_ALL_POOLS = "maxUpdateAfterBindDescriptorsInAllPools";
    public static final String KEY_MAX_VERTEX_ATTRIB_DIVISOR = "maxVertexAttribDivisor";
    public static final String KEY_MAX_VERTEX_INPUT_ATTRIBUTES = "maxVertexInputAttributes";
    public static final String KEY_MAX_VERTEX_INPUT_ATTRIBUTE_OFFSET = "maxVertexInputAttributeOffset";
    public static final String KEY_MAX_VERTEX_INPUT_BINDINGS = "maxVertexInputBindings";
    public static final String KEY_MAX_VERTEX_INPUT_BINDING_STRIDE = "maxVertexInputBindingStride";
    public static final String KEY_MAX_VERTEX_OUTPUT_COMPONENTS = "maxVertexOutputComponents";
    public static final String KEY_MAX_VIEWPORTS = "maxViewports";
    public static final String KEY_MAX_VIEWPORT_DIMENSIONS = "maxViewportDimensions";
    public static final String KEY_MEMORY = "memory";
    public static final String KEY_MEMORY_HEAPS = "memoryHeaps";
    public static final String KEY_MEMORY_HEAP_COUNT = "memoryHeapCount";
    public static final String KEY_MEMORY_TYPES = "memoryTypes";
    public static final String KEY_MEMORY_TYPE_COUNT = "memoryTypeCount";
    public static final String KEY_MINOR = "minor";
    public static final String KEY_MIN_IMAGE_TRANSFER_GRANULARITY = "minImageTransferGranularity";
    public static final String KEY_MIN_INTERPOLATION_OFFSET = "minInterpolationOffset";
    public static final String KEY_MIN_MEMORY_MAP_ALIGNMENT = "minMemoryMapAlignment";
    public static final String KEY_MIN_STORAGE_BUFFER_OFFSET_ALIGNMENT = "minStorageBufferOffsetAlignment";
    public static final String KEY_MIN_SUBGROUP_SIZE = "minSubgroupSize";
    public static final String KEY_MIN_TEXEL_BUFFER_OFFSET_ALIGNMENT = "minTexelBufferOffsetAlignment";
    public static final String KEY_MIN_TEXEL_GATHER_OFFSET = "minTexelGatherOffset";
    public static final String KEY_MIN_TEXEL_OFFSET = "minTexelOffset";
    public static final String KEY_MIN_UNIFORM_BUFFER_OFFSET_ALIGNMENT = "minUniformBufferOffsetAlignment";
    public static final String KEY_MIPMAP_PRECISION_BITS = "mipmapPrecisionBits";
    public static final String KEY_MULTIVIEW = "multiview";
    public static final String KEY_MULTIVIEW_FEATURES = "multiviewFeatures";
    public static final String KEY_MULTIVIEW_GEOMETRY_SHADER = "multiviewGeometryShader";
    public static final String KEY_MULTIVIEW_PROPERTIES = "multiviewProperties";
    public static final String KEY_MULTIVIEW_TESSELLATION_SHADER = "multiviewTessellationShader";
    public static final String KEY_MULTI_DRAW_INDIRECT = "multiDrawIndirect";
    public static final String KEY_MULTI_VIEWPORT = "multiViewport";
    public static final String KEY_NON_COHERENT_ATOM_SIZE = "nonCoherentAtomSize";
    public static final String KEY_NON_STRICT_SINGLE_PIXEL_WIDE_LINES_USE_PARALLELOGRAM = "nonStrictSinglePixelWideLinesUseParallelogram";
    public static final String KEY_NON_STRICT_WIDE_LINES_USE_PARALLELOGRAM = "nonStrictWideLinesUseParallelogram";
    public static final String KEY_OCCLUSION_QUERY_PRECISE = "occlusionQueryPrecise";
    public static final String KEY_OPTIMAL_BUFFER_COPY_OFFSET_ALIGNMENT = "optimalBufferCopyOffsetAlignment";
    public static final String KEY_OPTIMAL_BUFFER_COPY_ROW_PITCH_ALIGNMENT = "optimalBufferCopyRowPitchAlignment";
    public static final String KEY_OPTIMAL_TILING_FEATURES = "optimalTilingFeatures";
    public static final String KEY_OPTIMAL_TILING_LAYOUT_UUID = "optimalTilingLayoutUUID";
    public static final String KEY_PATCH = "patch";
    public static final String KEY_PIPELINE_CACHE_UUID = "pipelineCacheUUID";
    public static final String KEY_PIPELINE_CREATION_CACHE_CONTROL = "pipelineCreationCacheControl";
    public static final String KEY_PIPELINE_PROTECTED_ACCESS = "pipelineProtectedAccess";
    public static final String KEY_PIPELINE_ROBUSTNESS = "pipelineRobustness";
    public static final String KEY_PIPELINE_STATISTICS_QUERY = "pipelineStatisticsQuery";
    public static final String KEY_POINT_CLIPPING_BEHAVIOR = "pointClippingBehavior";
    public static final String KEY_POINT_CLIPPING_PROPERTIES = "pointClippingProperties";
    public static final String KEY_POINT_SIZE_GRANULARITY = "pointSizeGranularity";
    public static final String KEY_POINT_SIZE_RANGE = "pointSizeRange";
    public static final String KEY_POLYGON_MODE_POINT_SIZE = "polygonModePointSize";
    public static final String KEY_PRIMITIVES_GENERATED_QUERY = "primitivesGeneratedQuery";
    public static final String KEY_PRIMITIVES_GENERATED_QUERY_FEATURES_EXT = "primitivesGeneratedQueryFeaturesEXT";
    public static final String KEY_PRIMITIVES_GENERATED_QUERY_WITH_NON_ZERO_STREAMS = "primitivesGeneratedQueryWithNonZeroStreams";
    public static final String KEY_PRIMITIVES_GENERATED_QUERY_WITH_RASTERIZER_DISCARD = "primitivesGeneratedQueryWithRasterizerDiscard";
    public static final String KEY_PRIMITIVE_TOPOLOGY_LIST_RESTART = "primitiveTopologyListRestart";
    public static final String KEY_PRIMITIVE_TOPOLOGY_LIST_RESTART_FEATURES_EXT = "primitiveTopologyListRestartFeaturesEXT";
    public static final String KEY_PRIMITIVE_TOPOLOGY_PATCH_LIST_RESTART = "primitiveTopologyPatchListRestart";
    public static final String KEY_PRIVATE_DATA = "privateData";
    public static final String KEY_PROPERTIES = "properties";
    public static final String KEY_PROPERTY_FLAGS = "propertyFlags";
    public static final String KEY_PROTECTED_MEMORY = "protectedMemory";
    public static final String KEY_PROTECTED_MEMORY_FEATURES = "protectedMemoryFeatures";
    public static final String KEY_PROTECTED_NO_FAULT = "protectedNoFault";
    public static final String KEY_PROVOKING_VERTEX_FEATURES_EXT = "provokingVertexFeaturesEXT";
    public static final String KEY_PROVOKING_VERTEX_LAST = "provokingVertexLast";
    public static final String KEY_PUSH_DESCRIPTOR = "pushDescriptor";
    public static final String KEY_P_COPY_DST_LAYOUTS = "pCopyDstLayouts";
    public static final String KEY_P_COPY_SRC_LAYOUTS = "pCopySrcLayouts";
    public static final String KEY_QUAD_DIVERGENT_IMPLICIT_LOD = "quadDivergentImplicitLod";
    public static final String KEY_QUAD_OPERATIONS_IN_ALL_STAGES = "quadOperationsInAllStages";
    public static final String KEY_QUEUES = "queues";
    public static final String KEY_QUEUE_COUNT = "queueCount";
    public static final String KEY_QUEUE_FLAGS = "queueFlags";
    public static final String KEY_RECTANGULAR_LINES = "rectangularLines";
    public static final String KEY_RELAXED_LINE_RASTERIZATION = "relaxedLineRasterization";
    public static final String KEY_RELAXED_LINE_RASTERIZATION_FEATURES_IMG = "relaxedLineRasterizationFeaturesIMG";
    public static final String KEY_REQUIRED_SUBGROUP_SIZE_STAGES = "requiredSubgroupSizeStages";
    public static final String KEY_RESIDENCY_ALIGNED_MIP_SIZE = "residencyAlignedMipSize";
    public static final String KEY_RESIDENCY_NON_RESIDENT_STRICT = "residencyNonResidentStrict";
    public static final String KEY_RESIDENCY_STANDARD_2D_BLOCK_SHAPE = "residencyStandard2DBlockShape";
    public static final String KEY_RESIDENCY_STANDARD_2D_MULTISAMPLE_BLOCK_SHAPE = "residencyStandard2DMultisampleBlockShape";
    public static final String KEY_RESIDENCY_STANDARD_3D_BLOCK_SHAPE = "residencyStandard3DBlockShape";
    public static final String KEY_ROBUST_BUFFER_ACCESS = "robustBufferAccess";
    public static final String KEY_ROBUST_BUFFER_ACCESS_UPDATE_AFTER_BIND = "robustBufferAccessUpdateAfterBind";
    public static final String KEY_ROBUST_IMAGE_ACCESS = "robustImageAccess";
    public static final String KEY_ROUNDING_MODE_INDEPENDENCE = "roundingModeIndependence";
    public static final String KEY_RUNTIME_DESCRIPTOR_ARRAY = "runtimeDescriptorArray";
    public static final String KEY_SAMPLED_IMAGE_COLOR_SAMPLE_COUNTS = "sampledImageColorSampleCounts";
    public static final String KEY_SAMPLED_IMAGE_DEPTH_SAMPLE_COUNTS = "sampledImageDepthSampleCounts";
    public static final String KEY_SAMPLED_IMAGE_INTEGER_SAMPLE_COUNTS = "sampledImageIntegerSampleCounts";
    public static final String KEY_SAMPLED_IMAGE_STENCIL_SAMPLE_COUNTS = "sampledImageStencilSampleCounts";
    public static final String KEY_SAMPLER_2D_VIEW_OF_3D = "sampler2DViewOf3D";
    public static final String KEY_SAMPLER_ANISOTROPY = "samplerAnisotropy";
    public static final String KEY_SAMPLER_FILTER_MINMAX = "samplerFilterMinmax";
    public static final String KEY_SAMPLER_MIRROR_CLAMP_TO_EDGE = "samplerMirrorClampToEdge";
    public static final String KEY_SAMPLER_YCBCR_CONVERSION = "samplerYcbcrConversion";
    public static final String KEY_SAMPLER_YCBCR_CONVERSION_FEATURES = "samplerYcbcrConversionFeatures";
    public static final String KEY_SAMPLE_RATE_SHADING = "sampleRateShading";
    public static final String KEY_SCALAR_BLOCK_LAYOUT = "scalarBlockLayout";
    public static final String KEY_SEPARATE_DEPTH_STENCIL_LAYOUTS = "separateDepthStencilLayouts";
    public static final String KEY_SHADER_BUFFER_INT64_ATOMICS = "shaderBufferInt64Atomics";
    public static final String KEY_SHADER_CLIP_DISTANCE = "shaderClipDistance";
    public static final String KEY_SHADER_CULL_DISTANCE = "shaderCullDistance";
    public static final String KEY_SHADER_DEMOTE_TO_HELPER_INVOCATION = "shaderDemoteToHelperInvocation";
    public static final String KEY_SHADER_DENORM_FLUSH_TO_ZERO_FLOAT16 = "shaderDenormFlushToZeroFloat16";
    public static final String KEY_SHADER_DENORM_FLUSH_TO_ZERO_FLOAT32 = "shaderDenormFlushToZeroFloat32";
    public static final String KEY_SHADER_DENORM_FLUSH_TO_ZERO_FLOAT64 = "shaderDenormFlushToZeroFloat64";
    public static final String KEY_SHADER_DENORM_PRESERVE_FLOAT16 = "shaderDenormPreserveFloat16";
    public static final String KEY_SHADER_DENORM_PRESERVE_FLOAT32 = "shaderDenormPreserveFloat32";
    public static final String KEY_SHADER_DENORM_PRESERVE_FLOAT64 = "shaderDenormPreserveFloat64";
    public static final String KEY_SHADER_DRAW_PARAMETERS = "shaderDrawParameters";
    public static final String KEY_SHADER_DRAW_PARAMETER_FEATURES = "shaderDrawParameterFeatures";
    public static final String KEY_SHADER_EXPECT_ASSUME = "shaderExpectAssume";
    public static final String KEY_SHADER_FLOAT16 = "shaderFloat16";
    public static final String KEY_SHADER_FLOAT16_INT8_FEATURES_KHR = "shaderFloat16Int8FeaturesKHR";
    public static final String KEY_SHADER_FLOAT64 = "shaderFloat64";
    public static final String KEY_SHADER_FLOAT_CONTROLS2 = "shaderFloatControls2";
    public static final String KEY_SHADER_IMAGE_GATHER_EXTENDED = "shaderImageGatherExtended";
    public static final String KEY_SHADER_INPUT_ATTACHMENT_ARRAY_DYNAMIC_INDEXING = "shaderInputAttachmentArrayDynamicIndexing";
    public static final String KEY_SHADER_INPUT_ATTACHMENT_ARRAY_NONUNIFORM_INDEXING_NATIVE = "shaderInputAttachmentArrayNonUniformIndexingNative";
    public static final String KEY_SHADER_INPUT_ATTACHMENT_ARRAY_NON_UNIFORM_INDEXING = "shaderInputAttachmentArrayNonUniformIndexing";
    public static final String KEY_SHADER_INT16 = "shaderInt16";
    public static final String KEY_SHADER_INT64 = "shaderInt64";
    public static final String KEY_SHADER_INT8 = "shaderInt8";
    public static final String KEY_SHADER_INTEGER_DOT_PRODUCT = "shaderIntegerDotProduct";
    public static final String KEY_SHADER_INTEGER_DOT_PRODUCT_FEATURES_KHR = "shaderIntegerDotProductFeaturesKHR";
    public static final String KEY_SHADER_OUTPUT_LAYER = "shaderOutputLayer";
    public static final String KEY_SHADER_OUTPUT_VIEWPORT_INDEX = "shaderOutputViewportIndex";
    public static final String KEY_SHADER_RESOURCE_MIN_LOD = "shaderResourceMinLod";
    public static final String KEY_SHADER_RESOURCE_RESIDENCY = "shaderResourceResidency";
    public static final String KEY_SHADER_ROUNDING_MODE_RTE_FLOAT16 = "shaderRoundingModeRTEFloat16";
    public static final String KEY_SHADER_ROUNDING_MODE_RTE_FLOAT32 = "shaderRoundingModeRTEFloat32";
    public static final String KEY_SHADER_ROUNDING_MODE_RTE_FLOAT64 = "shaderRoundingModeRTEFloat64";
    public static final String KEY_SHADER_ROUNDING_MODE_RTZ_FLOAT16 = "shaderRoundingModeRTZFloat16";
    public static final String KEY_SHADER_ROUNDING_MODE_RTZ_FLOAT32 = "shaderRoundingModeRTZFloat32";
    public static final String KEY_SHADER_ROUNDING_MODE_RTZ_FLOAT64 = "shaderRoundingModeRTZFloat64";
    public static final String KEY_SHADER_SAMPLED_IMAGE_ARRAY_DYNAMIC_INDEXING = "shaderSampledImageArrayDynamicIndexing";
    public static final String KEY_SHADER_SAMPLED_IMAGE_ARRAY_NONUNIFORM_INDEXING_NATIVE = "shaderSampledImageArrayNonUniformIndexingNative";
    public static final String KEY_SHADER_SAMPLED_IMAGE_ARRAY_NON_UNIFORM_INDEXING = "shaderSampledImageArrayNonUniformIndexing";
    public static final String KEY_SHADER_SHARED_INT64_ATOMICS = "shaderSharedInt64Atomics";
    public static final String KEY_SHADER_SIGNED_ZERO_INF_NAN_PRESERVE_FLOAT16 = "shaderSignedZeroInfNanPreserveFloat16";
    public static final String KEY_SHADER_SIGNED_ZERO_INF_NAN_PRESERVE_FLOAT32 = "shaderSignedZeroInfNanPreserveFloat32";
    public static final String KEY_SHADER_SIGNED_ZERO_INF_NAN_PRESERVE_FLOAT64 = "shaderSignedZeroInfNanPreserveFloat64";
    public static final String KEY_SHADER_STORAGE_BUFFER_ARRAY_DYNAMIC_INDEXING = "shaderStorageBufferArrayDynamicIndexing";
    public static final String KEY_SHADER_STORAGE_BUFFER_ARRAY_NONUNIFORM_INDEXING_NATIVE = "shaderStorageBufferArrayNonUniformIndexingNative";
    public static final String KEY_SHADER_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING = "shaderStorageBufferArrayNonUniformIndexing";
    public static final String KEY_SHADER_STORAGE_IMAGE_ARRAY_DYNAMIC_INDEXING = "shaderStorageImageArrayDynamicIndexing";
    public static final String KEY_SHADER_STORAGE_IMAGE_ARRAY_NONUNIFORM_INDEXING_NATIVE = "shaderStorageImageArrayNonUniformIndexingNative";
    public static final String KEY_SHADER_STORAGE_IMAGE_ARRAY_NON_UNIFORM_INDEXING = "shaderStorageImageArrayNonUniformIndexing";
    public static final String KEY_SHADER_STORAGE_IMAGE_EXTENDED_FORMATS = "shaderStorageImageExtendedFormats";
    public static final String KEY_SHADER_STORAGE_IMAGE_MULTISAMPLE = "shaderStorageImageMultisample";
    public static final String KEY_SHADER_STORAGE_IMAGE_READ_WITHOUT_FORMAT = "shaderStorageImageReadWithoutFormat";
    public static final String KEY_SHADER_STORAGE_IMAGE_WRITE_WITHOUT_FORMAT = "shaderStorageImageWriteWithoutFormat";
    public static final String KEY_SHADER_STORAGE_TEXEL_BUFFER_ARRAY_DYNAMIC_INDEXING = "shaderStorageTexelBufferArrayDynamicIndexing";
    public static final String KEY_SHADER_STORAGE_TEXEL_BUFFER_ARRAY_NON_UNIFORM_INDEXING = "shaderStorageTexelBufferArrayNonUniformIndexing";
    public static final String KEY_SHADER_SUBGROUP_EXTENDED_TYPES = "shaderSubgroupExtendedTypes";
    public static final String KEY_SHADER_SUBGROUP_EXTENDED_TYPES_FEATURES_KHR = "shaderSubgroupExtendedTypesFeaturesKHR";
    public static final String KEY_SHADER_SUBGROUP_ROTATE = "shaderSubgroupRotate";
    public static final String KEY_SHADER_SUBGROUP_ROTATE_CLUSTERED = "shaderSubgroupRotateClustered";
    public static final String KEY_SHADER_SUBGROUP_UNIFORM_CONTROL_FLOW = "shaderSubgroupUniformControlFlow";
    public static final String KEY_SHADER_SUBGROUP_UNIFORM_CONTROL_FLOW_FEATURES_KHR = "shaderSubgroupUniformControlFlowFeaturesKHR";
    public static final String KEY_SHADER_TERMINATE_INVOCATION = "shaderTerminateInvocation";
    public static final String KEY_SHADER_TESSELLATION_AND_GEOMETRY_POINT_SIZE = "shaderTessellationAndGeometryPointSize";
    public static final String KEY_SHADER_UNIFORM_BUFFER_ARRAY_DYNAMIC_INDEXING = "shaderUniformBufferArrayDynamicIndexing";
    public static final String KEY_SHADER_UNIFORM_BUFFER_ARRAY_NONUNIFORM_INDEXING_NATIVE = "shaderUniformBufferArrayNonUniformIndexingNative";
    public static final String KEY_SHADER_UNIFORM_BUFFER_ARRAY_NON_UNIFORM_INDEXING = "shaderUniformBufferArrayNonUniformIndexing";
    public static final String KEY_SHADER_UNIFORM_TEXEL_BUFFER_ARRAY_DYNAMIC_INDEXING = "shaderUniformTexelBufferArrayDynamicIndexing";
    public static final String KEY_SHADER_UNIFORM_TEXEL_BUFFER_ARRAY_NON_UNIFORM_INDEXING = "shaderUniformTexelBufferArrayNonUniformIndexing";
    public static final String KEY_SHADER_ZERO_INITIALIZE_WORKGROUP_MEMORY = "shaderZeroInitializeWorkgroupMemory";
    public static final String KEY_SIZE = "size";
    public static final String KEY_SMOOTH_LINES = "smoothLines";
    public static final String KEY_SPARSE_ADDRESS_SPACE_SIZE = "sparseAddressSpaceSize";
    public static final String KEY_SPARSE_BINDING = "sparseBinding";
    public static final String KEY_SPARSE_PROPERTIES = "sparseProperties";
    public static final String KEY_SPARSE_RESIDENCY_16_SAMPLES = "sparseResidency16Samples";
    public static final String KEY_SPARSE_RESIDENCY_2_SAMPLES = "sparseResidency2Samples";
    public static final String KEY_SPARSE_RESIDENCY_4_SAMPLES = "sparseResidency4Samples";
    public static final String KEY_SPARSE_RESIDENCY_8_SAMPLES = "sparseResidency8Samples";
    public static final String KEY_SPARSE_RESIDENCY_ALIASED = "sparseResidencyAliased";
    public static final String KEY_SPARSE_RESIDENCY_BUFFER = "sparseResidencyBuffer";
    public static final String KEY_SPARSE_RESIDENCY_IMAGE_2D = "sparseResidencyImage2D";
    public static final String KEY_SPARSE_RESIDENCY_IMAGE_3D = "sparseResidencyImage3D";
    public static final String KEY_SPEC_VERSION = "specVersion";
    public static final String KEY_STANDARD_SAMPLE_LOCATIONS = "standardSampleLocations";
    public static final String KEY_STIPPLED_BRESENHAM_LINES = "stippledBresenhamLines";
    public static final String KEY_STIPPLED_RECTANGULAR_LINES = "stippledRectangularLines";
    public static final String KEY_STIPPLED_SMOOTH_LINES = "stippledSmoothLines";
    public static final String KEY_STORAGE_BUFFER_16BIT_ACCESS = "storageBuffer16BitAccess";
    public static final String KEY_STORAGE_BUFFER_8BIT_ACCESS = "storageBuffer8BitAccess";
    public static final String KEY_STORAGE_IMAGE_SAMPLE_COUNTS = "storageImageSampleCounts";
    public static final String KEY_STORAGE_INPUT_OUTPUT_16 = "storageInputOutput16";
    public static final String KEY_STORAGE_PUSH_CONSTANT8 = "storagePushConstant8";
    public static final String KEY_STORAGE_PUSH_CONSTANT_16 = "storagePushConstant16";
    public static final String KEY_STORAGE_TEXEL_BUFFER_OFFSET_ALIGNMENT_BYTES = "storageTexelBufferOffsetAlignmentBytes";
    public static final String KEY_STORAGE_TEXEL_BUFFER_OFFSET_SINGLE_TEXEL_ALIGNMENT = "storageTexelBufferOffsetSingleTexelAlignment";
    public static final String KEY_STRICT_LINES = "strictLines";
    public static final String KEY_SUBGROUP_BROADCAST_DYNAMIC_ID = "subgroupBroadcastDynamicId";
    public static final String KEY_SUBGROUP_PROPERTIES = "subgroupProperties";
    public static final String KEY_SUBGROUP_QUAD_OPERATIONS_IN_ALL_STAGES = "subgroupQuadOperationsInAllStages";
    public static final String KEY_SUBGROUP_SIZE = "subgroupSize";
    public static final String KEY_SUBGROUP_SIZE_CONTROL = "subgroupSizeControl";
    public static final String KEY_SUBGROUP_SUPPORTED_OPERATIONS = "subgroupSupportedOperations";
    public static final String KEY_SUBGROUP_SUPPORTED_STAGES = "subgroupSupportedStages";
    public static final String KEY_SUBMINOR = "subminor";
    public static final String KEY_SUBSET_ALLOCATION = "subsetAllocation";
    public static final String KEY_SUB_PIXEL_INTERPOLATION_OFFSET_BITS = "subPixelInterpolationOffsetBits";
    public static final String KEY_SUB_PIXEL_PRECISION_BITS = "subPixelPrecisionBits";
    public static final String KEY_SUB_TEXEL_PRECISION_BITS = "subTexelPrecisionBits";
    public static final String KEY_SUPPORTED_DEPTH_RESOLVE_MODES = "supportedDepthResolveModes";
    public static final String KEY_SUPPORTED_OPERATIONS = "supportedOperations";
    public static final String KEY_SUPPORTED_STAGES = "supportedStages";
    public static final String KEY_SUPPORTED_STENCIL_RESOLVE_MODES = "supportedStencilResolveModes";
    public static final String KEY_SUPPORTS_NON_ZERO_FIRST_INSTANCE = "supportsNonZeroFirstInstance";
    public static final String KEY_SYNCHRONIZATION2 = "synchronization2";
    public static final String KEY_TESSELLATION_SHADER = "tessellationShader";
    public static final String KEY_TEXTURE_COMPRESSION_ASTC_HDR = "textureCompressionASTC_HDR";
    public static final String KEY_TEXTURE_COMPRESSION_ASTC_LDR = "textureCompressionASTC_LDR";
    public static final String KEY_TEXTURE_COMPRESSION_BC = "textureCompressionBC";
    public static final String KEY_TEXTURE_COMPRESSION_ETC2 = "textureCompressionETC2";
    public static final String KEY_TIMELINE_SEMAPHORE = "timelineSemaphore";
    public static final String KEY_TIMESTAMP_COMPUTE_AND_GRAPHICS = "timestampComputeAndGraphics";
    public static final String KEY_TIMESTAMP_PERIOD = "timestampPeriod";
    public static final String KEY_TIMESTAMP_VALID_BITS = "timestampValidBits";
    public static final String KEY_TRANSFORM_FEEDBACK = "transformFeedback";
    public static final String KEY_TRANSFORM_FEEDBACK_FEATURES_EXT = "transformFeedbackFeaturesEXT";
    public static final String KEY_TRANSFORM_FEEDBACK_PRESERVES_PROVOKING_VERTEX = "transformFeedbackPreservesProvokingVertex";
    public static final String KEY_UNIFORM_AND_STORAGE_BUFFER_16BIT_ACCESS = "uniformAndStorageBuffer16BitAccess";
    public static final String KEY_UNIFORM_AND_STORAGE_BUFFER_8BIT_ACCESS = "uniformAndStorageBuffer8BitAccess";
    public static final String KEY_UNIFORM_BUFFER_STANDARD_LAYOUT = "uniformBufferStandardLayout";
    public static final String KEY_UNIFORM_TEXEL_BUFFER_OFFSET_ALIGNMENT_BYTES = "uniformTexelBufferOffsetAlignmentBytes";
    public static final String KEY_UNIFORM_TEXEL_BUFFER_OFFSET_SINGLE_TEXEL_ALIGNMENT = "uniformTexelBufferOffsetSingleTexelAlignment";
    public static final String KEY_VARIABLE_MULTISAMPLE_RATE = "variableMultisampleRate";
    public static final String KEY_VARIABLE_POINTERS = "variablePointers";
    public static final String KEY_VARIABLE_POINTERS_FEATURES = "variablePointersFeatures";
    public static final String KEY_VARIABLE_POINTERS_FEATURES_KHR = "variablePointersFeaturesKHR";
    public static final String KEY_VARIABLE_POINTERS_STORAGE_BUFFER = "variablePointersStorageBuffer";
    public static final String KEY_VARIABLE_POINTER_FEATURES_KHR = "variablePointerFeaturesKHR";
    public static final String KEY_VENDOR_ID = "vendorID";
    public static final String KEY_VERTEX_ATTRIBUTE_DIVISOR_FEATURES_KHR = "vertexAttributeDivisorFeaturesKHR";
    public static final String KEY_VERTEX_ATTRIBUTE_INSTANCE_RATE_DIVISOR = "vertexAttributeInstanceRateDivisor";
    public static final String KEY_VERTEX_ATTRIBUTE_INSTANCE_RATE_ZERO_DIVISOR = "vertexAttributeInstanceRateZeroDivisor";
    public static final String KEY_VERTEX_PIPELINE_STORES_AND_ATOMICS = "vertexPipelineStoresAndAtomics";
    public static final String KEY_VIEWPORT_BOUNDS_RANGE = "viewportBoundsRange";
    public static final String KEY_VIEWPORT_SUB_PIXEL_BITS = "viewportSubPixelBits";
    public static final String KEY_VK_EXT_CUSTOM_BORDER_COLOR = "VK_EXT_custom_border_color";
    public static final String KEY_VK_EXT_IMAGE_2D_VIEW_OF_3D = "VK_EXT_image_2d_view_of_3d";
    public static final String KEY_VK_EXT_INDEX_TYPE_UINT8 = "VK_EXT_index_type_uint8";
    public static final String KEY_VK_EXT_LINE_RASTERIZATION = "VK_EXT_line_rasterization";
    public static final String KEY_VK_EXT_PRIMITIVES_GENERATED_QUERY = "VK_EXT_primitives_generated_query";
    public static final String KEY_VK_EXT_PRIMITIVE_TOPOLOGY_LIST_RESTART = "VK_EXT_primitive_topology_list_restart";
    public static final String KEY_VK_EXT_PROVOKING_VERTEX = "VK_EXT_provoking_vertex";
    public static final String KEY_VK_EXT_TRANSFORM_FEEDBACK = "VK_EXT_transform_feedback";
    public static final String KEY_VK_IMG_RELAXED_LINE_RASTERIZATION = "VK_IMG_relaxed_line_rasterization";
    public static final String KEY_VK_KHR_8BIT_STORAGE = "VK_KHR_8bit_storage";
    public static final String KEY_VK_KHR_DRIVER_PROPERTIES = "VK_KHR_driver_properties";
    public static final String KEY_VK_KHR_INDEX_TYPE_UINT8 = "VK_KHR_index_type_uint8";
    public static final String KEY_VK_KHR_SHADER_FLOAT16_INT8 = "VK_KHR_shader_float16_int8";
    public static final String KEY_VK_KHR_SHADER_FLOAT_CONTROLS = "VK_KHR_shader_float_controls";
    public static final String KEY_VK_KHR_SHADER_INTEGER_DOT_PRODUCT = "VK_KHR_shader_integer_dot_product";
    public static final String KEY_VK_KHR_SHADER_SUBGROUP_EXTENDED_TYPES = "VK_KHR_shader_subgroup_extended_types";
    public static final String KEY_VK_KHR_SHADER_SUBGROUP_UNIFORM_CONTROL_FLOW = "VK_KHR_shader_subgroup_uniform_control_flow";
    public static final String KEY_VK_KHR_VARIABLE_POINTERS = "VK_KHR_variable_pointers";
    public static final String KEY_VK_KHR_VERTEX_ATTRIBUTE_DIVISOR = "VK_KHR_vertex_attribute_divisor";
    public static final String KEY_VULKAN_11_PROPERTIES = "vulkan_11_properties";
    public static final String KEY_VULKAN_11_FEATURES = "vulkan_11_features";
    public static final String KEY_VULKAN_12_FEATURES = "vulkan_12_features";
    public static final String KEY_VULKAN_12_PROPERTIES = "vulkan_12_properties";
    public static final String KEY_VULKAN_13_FEATURES = "vulkan_13_features";
    public static final String KEY_VULKAN_13_PROPERTIES = "vulkan_13_properties";
    public static final String KEY_VULKAN_14_FEATURES = "vulkan_14_features";
    public static final String KEY_VULKAN_14_PROPERTIES = "vulkan_14_properties";
    public static final String KEY_VULKAN_MEMORY_MODEL = "vulkanMemoryModel";
    public static final String KEY_VULKAN_MEMORY_MODEL_AVAILABILITY_VISIBILITY_CHAINS = "vulkanMemoryModelAvailabilityVisibilityChains";
    public static final String KEY_VULKAN_MEMORY_MODEL_DEVICE_SCOPE = "vulkanMemoryModelDeviceScope";
    public static final String KEY_WIDE_LINES = "wideLines";
    public static final String KEY_WIDTH = "width";

    public static final int VK_API_VERSION_1_1 = 4198400;
    public static final int VK_API_VERSION_1_2 = 4202496;
    public static final int VK_API_VERSION_1_3 = 4206592;
    public static final int VK_API_VERSION_1_4 = 4210688;

    private static Map<String, String> keyToConvertedName;

    static {
        createKeyToConvertedNameMap();
    }

    // Creates a map of vkjson names and VulkanDeviceInfo names
    private static void createKeyToConvertedNameMap() {
        keyToConvertedName = new HashMap<>();

        // Loop over all the constants of VulkanDeviceInfo
        for (Field field : VulkanDeviceInfoUtils.class.getDeclaredFields()) {
            if (field.getName().startsWith("KEY_")) {
                try {
                    String fieldName = field.getName();
                    String value = (String) field.get(null);
                    String convertedName = fieldName.replaceFirst("KEY_", "").toLowerCase(Locale.ROOT);
                    keyToConvertedName.put(value, convertedName);
                } catch (IllegalAccessException e) {
                    e.printStackTrace();
                    throw new RuntimeException(e);
                }
            }
        }

        // Special case
        keyToConvertedName.put(KEY_VARIABLE_POINTERS_FEATURES, "variable_pointer_features");
    }

    public static String getConvertedName(String name) {
        if (keyToConvertedName.containsKey(name)) {
            return keyToConvertedName.get(name);
        }
        else {
            throw new RuntimeException("unknown key name: " + name);
        }
    }
}